name: Node

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'REEff'     
# on:
#   repository_dispatch:
#     types: [my-event]
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/checkout@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     -  run: |
#         echo  ${{ github.ref }}
#     - run: |
#         echo  ${{ github.event.client_payload.ref }}
#        echo ${{ github.event.sender }}
#     - run: npm ci
#     - run: npm test
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo ${{ github.inputs.client_payload.ref }}
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - run: echo ${{ github.event.client_payload.ref }}
