name: Node

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'REEff'     
  
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    -  run: |
        echo " ${{ github.event.args.ref }} "
    - run: |
        echo "Log level: ${{ github.event.inputs.ref }}"
        echo ${{ github.event.ref }}
    - run: npm ci
    - run: npm test
