name: Node

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    -  run: |
        echo " ${{ github.event.client_payload.ref_name }} "
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo ${{ github.event.client_payload }}
    - run: npm ci
    - run: npm test
